---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-password
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgADcr14M0Fw6F0udbiMY79PvByJtZU/2wExQLYMr5c2Aws/a9Ts+uDZ1C+SiF/vF/dkJrTRGjrDTEQiL1CIL5wqecjxCovLvlPiFCEYXnGTlxAe8MQLv6PuH1WnSQbZYoP0waLt6H45ZVVHhdY3IQE/jxR3SzYW1p6EWlvLWZNNWpHGyOvdEhOIOefnqytqMrMo3pEPdu6UM8rrt+Y2R3nJLkSA/FA3qF2MjtHKGxVOLjD2A1+WYzrOgFWQnAx/a2z3pF230GxeIZ7o5PD59OrPcjBUeNclWhB4Lcz2Z2yGE6LTuHU/XaadY2JiD/rS3ePJHPNpF17Xjz7661IToJBDvHHcj/tOfvWmrxudmaeC2O5m5qy4e81x0tK9ZAtZkPYLfWGI2KuPvg1V+SO8Q02Q/qcgIujduaggl8HVPZEyGijfW6xhiKTkzfU2hrMpiPmNAmDYJ3a/o5rEU1NDy5IPmqSv6CP3pzZh/4Vkhgjtl18Wr7/RTwcjfYA+ncdJuFaXYosj1qh/9baqtlf23zyJWJ9P34CHlNRxyitfLvFavRTZBhWqpk9hWAeVZKD+HieoeIh9re67bAJwibGUp8giaxoHXAUSSnN/h10+npYxj0hL79EAG/3gIb9EQNgPSJN43W83pRE46fsEuqWzDtmqqdbDPBT5HJwSAgI9WJg3YMAgrVvUgIXw9PPPJieC6SHtP78HP9Df4ByPAw==
    admin-user: AgBWrnLa5XfOlWZzmU7DQTf+v+KJBbRlaBv//ATZHPXIBqYTx0tIGoAOPmHlclFcEpP9hFMIScY1xv/wS6kyiyqyWcwAdWNWc8abZcLQzURmNDC5DGGxGNdpEVjFY7LJVbJGQuEgT8ULqNSs3bF4LbFIf4MMJvE4c/0RLJC6xsTf8SbTeptzVclYFr+KWynYk9p/nh87scPmILABGLnWrLGO/6EFWYg/an7Rny91PgEIYMP5xuOjJRCZBsV5dHYOJ9JAT/Mw4IOjDnkPXGrGmzRnPaEHBfYr1W2sN/OSsm3XHizyqKOJGx2Sv+P+uqDzRI2LswvGtxzbDyna2hFDnGaBjj0Iyb1+P2Lr2NSRir/SOY0OD3JliurT5UESfiu1t4y3oUrNLvasPuYNiQiSaAotVqV0Jgh2kn4a+wzqZ+Q+CbI2L4rkY7TPdcczEZDQH1M/DJldVE9l2mZwocNV/2c8zCISOuxO2vGvPJWMuT26nGrYnwBIziF0fgEPtaBRgjUqPJFYbHmzrNZOcvEftdKDFhjRU9gT/dphmER0jyDBBUU86v6M5ERhe3R6hMYReA3qsOZywLsRF1ubY6v3L9sYteTOjIdmYVt+MsvmuZaDHyb+/nurbgcOm1bpKhssuY9vIy48Gt4HjLPu5cewEauN2H1jY7KlX7EEPDyooKLIcPqzWYd7RozVRhi1jwIdMXHReFQMMA==
  template:
    metadata:
      name: grafana-admin-password
      namespace: monitoring
