---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-password
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBKln9+QJzabFBV1NjdIx9IgddGPAe3s0Fr6G+ZWdPIuqjCCenB7go99cJPn/ws8KslZE99JQCMAR++FBGCkT1PO4h4CjKfwFvV9OgS6HV2DG6OtY+Q5C2/w5SRkdnmp0W5cBTqrElswHZTPkQfGhkIul3dcdrkeYVAcB0VvsBaE4pcetpcff/qdj7dkCbmUSnUCvIdve+i/ktqmYEVtUf4bRphZnvRNzponDTnhacnpusUtDjxUPXl82tvmPl+aggerpj29Yq1hNjBH4Qrf6x0yeyQlck3Cb+C6f1mN8VqesXpSsXnULozyxoyeS/awIOjeE1iUaA7TU30xGqejbxd04yfXOtRAnES8agMn7bAOg48vOQ1jvTzgL1GsC8uqo5vjnqU9UW8cfiFqXosGb6/mXPpKo9IuUacK7prHOSAIAbCSGq5wioHQJ7a64wcm8aCOWddX+UZ8fWHJc+8K/ZHxb1T854z/76AJ8kjsTOob/d/nhYJSg3q7oftZFW4Po9oIcT0H+CLSwdMVLIhZtR7zFRdvOFM8MU1c4dXsyTdvEFJkMMh1YLeWqOHzs7XhMS+duuZ/qRnzqaxzpA8m+ZLn+CzDtnECF8rrGBzAi7F5w5ihoPqibZL2oghG6wQ4XIZkmPy4wLrwrSnPiUkovky68n3KerTRhaGSfs0GvZKwICq9f5dereoHROkDKIbqn4HvIPqP6ClQg==
  template:
    metadata:
      name: grafana-admin-password
      namespace: monitoring
