apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gitops-infra
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/Shoukshai/GitOps
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-sources
  namespace: flux-system
spec:
  interval: 10m
  path: infrastructure/sources
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-infra
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-monitoring
  namespace: flux-system
spec:
  interval: 10m
  path: infrastructure/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-infra
  dependsOn:
    - name: infra-sources
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: kube-prometheus-stack
      namespace: flux-system
